### ISSUE TITLE
Please provide unzipped AppImage

### ISSUE THREAD

**Issue by probonopd** [Levoment/Dynagenic#1]
Hello, thanks for providing an AppImage.

We'd like it add it to https://appimage.github.io/ but for that we'd need you to please provide unzipped AppImage.

More information:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#common-mistake

**Comment by Levoment** [comment]
Hi,

Thanks for the feedback.

I have fixed the issue on release 1.1.2 together with other bugs the app had. The release which can be found here https://github.com/Levoment/Dynagenic/releases/tag/1.1.2 has the binary uploaded alone. The previous releases though still have the zipped AppImages.

**Comment by probonopd** [comment]
Thank you very much.
